### ISSUE TITLE
Changes are not reflected on saved file in editor

### ISSUE THREAD

**Issue by emahuni** [cloudcmd/deepword#1]
I have been trying cloud commander with deepword, which is my preffered editor. But the problem is that when I make a change and save it, close the file, the change isn't shown when I re-open the same file. Though the change is really committed to disk. Some times it doesn't commit to disk. I am not sure, but I think the software is reading from a buffer or something. It's reading the old contents, the unchanged content.

**Comment by emahuni** [comment]
I have noticed that when you press `ctrl + d` whilst in file manager, then open the file, it would have updated to its current contents. It seems like the error has something to do with local storage issues. Clearing local storage using the provided clear local storage shortcut before opening the file clears the buffer updates it correctly to its current contents. This is the current workaround for this.

**Comment by coderaiser** [comment]
Thank you :)

🔨 Fixed with 1d4f52f
✅ Landed in [v3.0.9](https://github.com/cloudcmd/deepword/releases/tag/v3.0.9)
