### ISSUE TITLE
Feature: dark theme

### ISSUE THREAD

**Issue by emahuni** [cloudcmd/deepword#2]
How to do you change theme to dark theme, something like vscode?

**Comment by coderaiser** [comment]
There is no such possibility, and I have no idea how to do this, looks like the answer should be in [docs](https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html).
It is definitely a great idea for a pull request :).

Could you please tell me how do you use `deepword`? As part of [cloudcmd](https://cloudcmd.io), as standalone editor or as a library?

**Comment by emahuni** [comment]
as a standalone editor.

I  use my tablet to code with termux as the terminal. Therefore I run cloudcmd in a terminal window and access it in the browser (Chrome) to modify files when needed.

I normally use Webstorm on Mac or emacs on the same terminal, but having vscode in the browser is great.

**Comment by coderaiser** [comment]
Added ability to override options with 3ac37fb.
Landed in [v4.1.0](https://github.com/cloudcmd/deepword/releases/tag/v4.1.0)🎉
